import { Inter } from "next/font/google";
import "./globals.css";
import FullScreen from "./components/fullScreen/fullScreen";
import store from "./store/index"

const inter = Inter({ subsets: ["latin"] });
import StoreProvider from "./store/storeProvider";
export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">

    <body className={inter.className}>
              <FullScreen />
              <StoreProvider>{children}</StoreProvider>

      </body>

    </html>
  );
}
